package com.sepidsa.fortytwocalculator.ui.history

import android.content.Intent
import android.os.Bundle
import android.view.LayoutInflater
import android.view.View
import android.view.ViewGroup
import androidx.compose.runtime.collectAsState
import androidx.compose.runtime.getValue
import androidx.compose.ui.platform.ComposeView
import androidx.fragment.app.Fragment
import androidx.fragment.app.activityViewModels
import androidx.fragment.app.viewModels
import com.sepidsa.fortytwocalculator.ui.calculator.CalculatorViewModel

class HistoryFragment : Fragment() {

    private val historyViewModel: HistoryViewModel by viewModels()
    private val calculatorViewModel: CalculatorViewModel by activityViewModels()

    override fun onCreateView(
        inflater: LayoutInflater,
        container: ViewGroup?,
        savedInstanceState: Bundle?
    ): View {
        return ComposeView(requireContext()).apply {
            setContent {
                val state by historyViewModel.uiState.collectAsState()
                HistoryScreen(
                    state = state,
                    onDelete = { historyViewModel.deleteLogEntry(it) },
                    onStarToggle = { id, starred -> historyViewModel.starLogEntry(id, starred) },
                    onUpdateTag = { id, tag -> historyViewModel.updateTag(id, tag) },
                    onUseEntry = { result ->
                        calculatorViewModel.addNumberToCalculation(result)
                    },
                    onClearAll = { clearStarred -> historyViewModel.clearHistory(clearStarred) },
                    onShare = { log ->
                        val shareText = buildString {
                            if (log.tag.isNotEmpty()) append("${log.tag}: ")
                            append("${log.operation} = ${log.result}")
                            if (log.starred != 0) append(" (*)")
                            append("\n\nGenerated by 42 calculator.")
                        }
                        val intent = Intent(Intent.ACTION_SEND).apply {
                            type = "text/plain"
                            putExtra(Intent.EXTRA_SUBJECT, "42 Calculation")
                            putExtra(Intent.EXTRA_TEXT, shareText)
                        }
                        startActivity(Intent.createChooser(intent, "Share"))
                    },
                    onFilterChange = { historyViewModel.setFilter(it) },
                )
            }
        }
    }
}
