apply plugin: 'com.android.application'

android {
    namespace 'com.sepidsa.fortytwocalculator'
    compileSdk 34

    defaultConfig {
        applicationId 'com.sepidsa.fortytwocalculator'
        minSdk 21
        targetSdk 34
        versionCode 23
        versionName '2.11'
    }

    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.txt'
        }
    }

    buildFeatures {
        aidl true
    }

    compileOptions {
        encoding 'UTF-8'
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
}

repositories {
    flatDir {
        dirs 'libs'
    }
}

configurations.all {
    exclude group: 'org.jetbrains.kotlin', module: 'kotlin-stdlib-jdk7'
    exclude group: 'org.jetbrains.kotlin', module: 'kotlin-stdlib-jdk8'
}

dependencies {
    implementation(name: 'library-2.4.1', ext: 'aar')
    implementation project(':library')

    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'androidx.core:core:1.13.1'
    implementation 'androidx.fragment:fragment:1.8.1'
    implementation 'androidx.loader:loader:1.1.0'
    implementation 'androidx.localbroadcastmanager:localbroadcastmanager:1.1.0'
    implementation 'androidx.viewpager:viewpager:1.0.0'
    implementation 'androidx.drawerlayout:drawerlayout:1.2.0'
    implementation 'org.jsoup:jsoup:1.17.2'
}
