package com.sepidsa.fortytwocalculator

import android.app.Activity
import android.content.ActivityNotFoundException
import android.content.ComponentName
import android.content.Context
import android.content.Intent
import android.graphics.Color
import android.media.AudioAttributes
import android.media.AudioManager
import android.media.SoundPool
import android.net.Uri
import android.os.Bundle
import android.os.Handler
import android.text.InputType
import android.util.Log
import android.view.KeyEvent
import android.view.View
import android.view.inputmethod.InputMethodManager
import android.widget.EditText
import android.widget.Toast
import androidx.activity.OnBackPressedCallback
import androidx.activity.enableEdgeToEdge
import androidx.activity.viewModels
import androidx.appcompat.app.AlertDialog
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.platform.ComposeView
import androidx.fragment.app.FragmentActivity
import androidx.lifecycle.Lifecycle
import androidx.lifecycle.compose.collectAsStateWithLifecycle
import androidx.lifecycle.lifecycleScope
import androidx.lifecycle.repeatOnLifecycle
import com.sepidsa.fortytwocalculator.data.ConstantEntity
import com.sepidsa.fortytwocalculator.data.SettingsRepository
import com.sepidsa.fortytwocalculator.ui.calculator.CalculatorUiEvent
import com.sepidsa.fortytwocalculator.ui.calculator.CalculatorViewModel
import com.sepidsa.fortytwocalculator.ui.calculator.SoundType
import com.sepidsa.fortytwocalculator.ui.constants.ConstantViewModel
import com.sepidsa.fortytwocalculator.ui.history.HistoryViewModel
import com.sepidsa.fortytwocalculator.ui.main.MainScreen
import com.sepidsa.fortytwocalculator.ui.theme.AppTheme
import com.sepidsa.fortytwocalculator.ui.dialogs.ColorPickerDialog
import kotlinx.coroutines.flow.collectLatest
import kotlinx.coroutines.launch
import java.io.File
import java.math.BigDecimal
import java.text.DecimalFormat
import java.text.DecimalFormatSymbols
import java.util.ArrayList
import java.util.Locale

class MainActivity : FragmentActivity() {

    private var mLatestInsertedId: Long = 0

    private lateinit var mSoundPool: SoundPool
    private var mSoundPoolLoaded: Boolean = false
    private var numericButtonSoundID: Int = 0
    private var executeButtonSoundID: Int = 0
    private var clearAllButtonSoundID: Int = 0
    private var operatorsButtonSoundID: Int = 0
    private var errorSoundID: Int = 0
    private var backSpaceButtonSoundID: Int = 0

    private var doubleBackToExitPressedOnce: Boolean = false
    private var mHandler: Handler? = null

    private val mRunnable = Runnable { doubleBackToExitPressedOnce = false }

    val historyViewModel: HistoryViewModel by viewModels()
    val constantViewModel: ConstantViewModel by viewModels()
    val calculatorViewModel: CalculatorViewModel by viewModels()
    private lateinit var settingsRepository: SettingsRepository

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        enableEdgeToEdge()

        settingsRepository = SettingsRepository(this)

        setContentView(ComposeView(this).apply {
            setContent {
                val calculatorState by calculatorViewModel.uiState.collectAsStateWithLifecycle()
                val historyState by historyViewModel.uiState.collectAsStateWithLifecycle()

                var showColorPicker by remember { mutableStateOf(false) }

                AppTheme {
                    MainScreen(
                        calculatorState = calculatorState,
                        historyState = historyState,
                        onCalculatorKeyPress = calculatorViewModel::onButtonPressed,
                        onAngleModeToggle = calculatorViewModel::setAngleMode,
                        onDeleteHistoryItem = historyViewModel::deleteLogEntry,
                        onStarHistoryItem = historyViewModel::starLogEntry,
                        onUpdateHistoryTag = historyViewModel::updateTag,
                        onClearHistory = historyViewModel::clearHistory,
                        onShareHistoryItem = { log ->
                            val shareText = buildString {
                                if (log.tag.isNotEmpty()) append("${log.tag}: ")
                                append("${log.operation} = ${log.result}")
                                if (log.starred != 0) append(" (*)")
                                append("\n\nGenerated by 42 calculator.")
                            }
                            val intent = Intent(Intent.ACTION_SEND).apply {
                                type = "text/plain"
                                putExtra(Intent.EXTRA_SUBJECT, "42 Calculation")
                                putExtra(Intent.EXTRA_TEXT, shareText)
                            }
                            startActivity(Intent.createChooser(intent, "Share"))
                        },
                        onUseHistoryEntry = calculatorViewModel::addNumberToCalculation,
                        onHistoryFilterChange = historyViewModel::setFilter,
                        onScientificKeyPress = calculatorViewModel::onButtonPressed,
                        onInverseToggle = { calculatorViewModel.setInverseMode(!calculatorState.inverseMode) },
                        onArcToggle = { calculatorViewModel.setArcMode(!calculatorState.arcMode) },
                        onConstantClick = { /* Show constants dialog */ },
                        onSettingsClick = {
                            // Settings dialog is now handled within MainScreen
                        },
                        onSettingsLanguageChanged = { langCode ->
                            calculatorViewModel.setLanguage(langCode)
                        },
                        onColorsClick = { showColorPicker = true },
                        onAddStarClick = {
                            lifecycleScope.launch {
                                historyViewModel.starLogEntry(mLatestInsertedId, true)
                            }
                        },
                        onAddLabelClick = {
                            showAddLabelDialog()
                        }
                    )

                    if (showColorPicker) {
                        ColorPickerDialog(
                            initialAccentColor = settingsRepository.accentColor,
                            initialKeypadColor = settingsRepository.keypadBackgroundColor,
                            isClassicTheme = settingsRepository.isClassicTheme,
                            onAcceptColors = { accentColor, keypadColor, useClassicTheme ->
                                settingsRepository.accentColor = accentColor
                                settingsRepository.keypadBackgroundColor = keypadColor
                                settingsRepository.isClassicTheme = useClassicTheme
                                // Recreate activity to apply new theme colors
                                recreate()
                            },
                            onDismiss = { showColorPicker = false }
                        )
                    }
                }
            }
        })

        observeViewModel()

        onBackPressedDispatcher.addCallback(this, object : OnBackPressedCallback(true) {
            override fun handleOnBackPressed() {
                if (doubleBackToExitPressedOnce) {
                    finish()
                    return
                }
                doubleBackToExitPressedOnce = true
                Toast.makeText(this@MainActivity, "دوباره لطفا", Toast.LENGTH_SHORT).show()
                mHandler = Handler()
                mHandler?.postDelayed(mRunnable, 2000)
            }
        })

        prepareSoundStuff()
        populateConstantDatabaseFirstRun()
    }

    private fun showAddLabelDialog() {
        lifecycleScope.launch {
            val logEntry = historyViewModel.getLogById(mLatestInsertedId)
            if (logEntry != null) {
                val currentLabel = logEntry.tag ?: ""
                val builder = AlertDialog.Builder(this@MainActivity)
                builder.setTitle(getString(R.string.farsi_label))

                val input = EditText(this@MainActivity)
                val inputMethodManager = getSystemService(Activity.INPUT_METHOD_SERVICE) as InputMethodManager

                input.inputType = InputType.TYPE_CLASS_TEXT
                builder.setView(input)
                builder.setCancelable(false)
                input.setText(currentLabel)
                input.requestFocus()
                inputMethodManager.toggleSoftInput(InputMethodManager.SHOW_FORCED, 0)

                builder.setPositiveButton(getString(R.string.farsi_ok)) { _, _ ->
                    val newLabel = input.text.toString()
                    historyViewModel.updateTag(mLatestInsertedId, newLabel)
                    inputMethodManager.hideSoftInputFromWindow(input.windowToken, 0)
                }
                builder.setNegativeButton(getString(R.string.farsi_cancel)) { dialog, _ ->
                    inputMethodManager.hideSoftInputFromWindow(input.windowToken, 0)
                    dialog.cancel()
                }
                val dialog = builder.create()
                dialog.show()
                val keyListener = View.OnKeyListener { _, keyCode, event ->
                    if (event.action == KeyEvent.ACTION_DOWN) {
                        when (keyCode) {
                            KeyEvent.KEYCODE_DPAD_CENTER,
                            KeyEvent.KEYCODE_ENTER -> {
                                dialog.getButton(AlertDialog.BUTTON_POSITIVE).performClick()
                                return@OnKeyListener true
                            }
                        }
                    }
                    false
                }
                input.setOnKeyListener(keyListener)
            }
        }
    }

    private fun observeViewModel() {
        lifecycleScope.launch {
            repeatOnLifecycle(Lifecycle.State.STARTED) {
                launch {
                    calculatorViewModel.uiEvents.collectLatest { event ->
                        handleUiEvent(event)
                    }
                }
                launch {
                    calculatorViewModel.newLogEntry.collectLatest { (expression, result, words) ->
                        mLatestInsertedId = historyViewModel.addLogEntry(expression, result, words).await()
                    }
                }
            }
        }
    }

    private fun handleUiEvent(event: CalculatorUiEvent) {
        when (event) {
            is CalculatorUiEvent.PlaySound -> {
                val soundId = when (event.soundType) {
                    SoundType.Numeric -> numericButtonSoundID
                    SoundType.Operator -> operatorsButtonSoundID
                    SoundType.Execute -> executeButtonSoundID
                    SoundType.Clear -> clearAllButtonSoundID
                    SoundType.Backspace -> backSpaceButtonSoundID
                    SoundType.Error -> errorSoundID
                }
                playSound(soundId)
            }
            else -> {}
        }
    }

    companion object {
        const val TAG: String = "mainactivity"
    }

    private fun populateConstantDatabaseFirstRun() {
        if (!settingsRepository.hasPopulatedConstantDatabase) {
            val names = resources.getStringArray(R.array.constant_default_names)
            val numbers = resources.getStringArray(R.array.constant_default_numbers)
            val selections = resources.getStringArray(R.array.constant_default_selections)

            for (index in names.indices) {
                constantViewModel.insertConstant(
                    ConstantEntity(
                        name = names[index],
                        number = numbers[index].toDouble(),
                        selected = selections[index].toInt()
                    )
                )
            }

            settingsRepository.hasPopulatedConstantDatabase = true
        }
    }

    fun playSound(id: Int) {
        val audioManager = getSystemService(Context.AUDIO_SERVICE) as AudioManager
        val ringerMode = audioManager.ringerMode
        
        if (ringerMode != AudioManager.RINGER_MODE_NORMAL) {
            return
        }

        val maxVolume = audioManager.getStreamMaxVolume(AudioManager.STREAM_MUSIC).toFloat()
        val volume = maxVolume // Full volume if not muted by system

        if (mSoundPoolLoaded) {
            mSoundPool.play(id, volume, volume, 1, 0, 0.99f)
        }
    }

    private fun prepareSoundStuff() {
        val attributes = AudioAttributes.Builder()
            .setUsage(AudioAttributes.USAGE_GAME)
            .setContentType(AudioAttributes.CONTENT_TYPE_SONIFICATION)
            .build()
        mSoundPool = SoundPool.Builder()
            .setAudioAttributes(attributes)
            .build()
        mSoundPool.setOnLoadCompleteListener { _, _, _ -> mSoundPoolLoaded = true }
        numericButtonSoundID = mSoundPool.load(applicationContext, R.raw.keypress, 1)
        executeButtonSoundID = mSoundPool.load(applicationContext, R.raw.equal, 1)
        clearAllButtonSoundID = mSoundPool.load(applicationContext, R.raw.clear, 1)
        operatorsButtonSoundID = mSoundPool.load(applicationContext, R.raw.keypress, 1)
        errorSoundID = mSoundPool.load(applicationContext, R.raw.error, 1)
        backSpaceButtonSoundID = mSoundPool.load(applicationContext, R.raw.backspace, 1)
    }
}
