package com.sepidsa.fortytwocalculator.ui.theme

import androidx.compose.ui.graphics.Color

val VoidLightPrimary = Color(0xFF006A5E)
val VoidLightOnPrimary = Color(0xFFFFFFFF)
val VoidLightPrimaryContainer = Color(0xFF9EF2E2)
val VoidLightOnPrimaryContainer = Color(0xFF00201B)
val VoidLightSecondary = Color(0xFF4A6360)
val VoidLightOnSecondary = Color(0xFFFFFFFF)
val VoidLightSecondaryContainer = Color(0xFFCCE8E2)
val VoidLightOnSecondaryContainer = Color(0xFF052020)
val VoidLightBackground = Color(0xFFF5FAF9)
val VoidLightOnBackground = Color(0xFF171D1C)
val VoidLightSurface = Color(0xFFF5FAF9)
val VoidLightOnSurface = Color(0xFF171D1C)
val VoidLightSurfaceVariant = Color(0xFFDAE5E3)
val VoidLightOnSurfaceVariant = Color(0xFF3F4948)
val VoidLightOutline = Color(0xFF6F7978)
val VoidLightError = Color(0xFFBA1A1A)
val VoidLightOnError = Color(0xFFFFFFFF)

val VoidDarkPrimary = Color(0xFF80D5C6)
val VoidDarkOnPrimary = Color(0xFF00372F)
val VoidDarkPrimaryContainer = Color(0xFF005048)
val VoidDarkOnPrimaryContainer = Color(0xFF9EF2E2)
val VoidDarkSecondary = Color(0xFFB1CCCA)
val VoidDarkOnSecondary = Color(0xFF1C3533)
val VoidDarkSecondaryContainer = Color(0xFF334B48)
val VoidDarkOnSecondaryContainer = Color(0xFFCCE8E2)
val VoidDarkBackground = Color(0xFF080808)
val VoidDarkOnBackground = Color(0xFFDDE4E2)
val VoidDarkSurface = Color(0xFF0E1413)
val VoidDarkOnSurface = Color(0xFFDDE4E2)
val VoidDarkSurfaceVariant = Color(0xFF3F4948)
val VoidDarkOnSurfaceVariant = Color(0xFFBEC9C7)
val VoidDarkOutline = Color(0xFF899392)
val VoidDarkError = Color(0xFFFFB4AB)
val VoidDarkOnError = Color(0xFF690005)
