package com.sepidsa.fortytwocalculator.ui.theme

import androidx.compose.material3.ColorScheme
import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

/**
 * Material 3 color schemes for each seed preset.
 * Colors derived from Material Theme Builder for each seed.
 */

// ============= TEAL (VOID brand color #1abc9c) =============
private val TealLight = lightColorScheme(
    primary = Color(0xFF006A5E),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFF9EF2E2),
    onPrimaryContainer = Color(0xFF00201B),
    secondary = Color(0xFF4A6360),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFCCE8E2),
    onSecondaryContainer = Color(0xFF052020),
    tertiary = Color(0xFF456179),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFCCE5FF),
    onTertiaryContainer = Color(0xFF001D31),
    error = Color(0xFFBA1A1A),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFFFDAD6),
    onErrorContainer = Color(0xFF410002),
    background = Color(0xFFF5FAF9),
    onBackground = Color(0xFF171D1C),
    surface = Color(0xFFF5FAF9),
    onSurface = Color(0xFF171D1C),
    surfaceVariant = Color(0xFFDAE5E3),
    onSurfaceVariant = Color(0xFF3F4948),
    outline = Color(0xFF6F7978),
    outlineVariant = Color(0xFFBEC9C7),
    scrim = Color(0xFF000000),
    inverseSurface = Color(0xFF2B3230),
    inverseOnSurface = Color(0xFFECF2F0),
    inversePrimary = Color(0xFF80D5C6),
    surfaceDim = Color(0xFFD5DBD9),
    surfaceBright = Color(0xFFF5FAF9),
    surfaceContainerLowest = Color(0xFFFFFFFF),
    surfaceContainerLow = Color(0xFFEFF5F3),
    surfaceContainer = Color(0xFFE9EFED),
    surfaceContainerHigh = Color(0xFFE3E9E7),
    surfaceContainerHighest = Color(0xFFDDE3E1),
)

private val TealDark = darkColorScheme(
    primary = Color(0xFF80D5C6),
    onPrimary = Color(0xFF00372F),
    primaryContainer = Color(0xFF005048),
    onPrimaryContainer = Color(0xFF9EF2E2),
    secondary = Color(0xFFB1CCCA),
    onSecondary = Color(0xFF1C3533),
    secondaryContainer = Color(0xFF334B48),
    onSecondaryContainer = Color(0xFFCCE8E2),
    tertiary = Color(0xFFACCAE5),
    onTertiary = Color(0xFF133349),
    tertiaryContainer = Color(0xFF2D4A61),
    onTertiaryContainer = Color(0xFFCCE5FF),
    error = Color(0xFFFFB4AB),
    onError = Color(0xFF690005),
    errorContainer = Color(0xFF93000A),
    onErrorContainer = Color(0xFFFFDAD6),
    background = Color(0xFF0E1513),
    onBackground = Color(0xFFDDE4E2),
    surface = Color(0xFF0E1513),
    onSurface = Color(0xFFDDE4E2),
    surfaceVariant = Color(0xFF3F4948),
    onSurfaceVariant = Color(0xFFBEC9C7),
    outline = Color(0xFF899392),
    outlineVariant = Color(0xFF3F4948),
    scrim = Color(0xFF000000),
    inverseSurface = Color(0xFFDDE4E2),
    inverseOnSurface = Color(0xFF2B3230),
    inversePrimary = Color(0xFF006A5E),
    surfaceDim = Color(0xFF0E1513),
    surfaceBright = Color(0xFF343B39),
    surfaceContainerLowest = Color(0xFF090F0E),
    surfaceContainerLow = Color(0xFF171D1C),
    surfaceContainer = Color(0xFF1B2120),
    surfaceContainerHigh = Color(0xFF252B2A),
    surfaceContainerHighest = Color(0xFF303635),
)

// ============= BLUE (#2563eb) =============
private val BlueLight = lightColorScheme(
    primary = Color(0xFF005CBC),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFD7E2FF),
    onPrimaryContainer = Color(0xFF001A40),
    secondary = Color(0xFF565E71),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFDAE2F9),
    onSecondaryContainer = Color(0xFF131B2C),
    tertiary = Color(0xFF705574),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFFAD8FD),
    onTertiaryContainer = Color(0xFF291331),
    error = Color(0xFFBA1A1A),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFFFDAD6),
    onErrorContainer = Color(0xFF410002),
    background = Color(0xFFFEFBFF),
    onBackground = Color(0xFF1B1B1F),
    surface = Color(0xFFFEFBFF),
    onSurface = Color(0xFF1B1B1F),
    surfaceVariant = Color(0xFFE1E2EC),
    onSurfaceVariant = Color(0xFF44474F),
    outline = Color(0xFF74777F),
    outlineVariant = Color(0xFFC4C6D0),
    scrim = Color(0xFF000000),
    inverseSurface = Color(0xFF303034),
    inverseOnSurface = Color(0xFFF2F0F4),
    inversePrimary = Color(0xFFACC7FF),
    surfaceDim = Color(0xFFDBD9DD),
    surfaceBright = Color(0xFFFEFBFF),
    surfaceContainerLowest = Color(0xFFFFFFFF),
    surfaceContainerLow = Color(0xFFF5F2F7),
    surfaceContainer = Color(0xFFEFEDF1),
    surfaceContainerHigh = Color(0xFFE9E7EB),
    surfaceContainerHighest = Color(0xFFE4E2E6),
)

private val BlueDark = darkColorScheme(
    primary = Color(0xFFACC7FF),
    onPrimary = Color(0xFF002F68),
    primaryContainer = Color(0xFF004493),
    onPrimaryContainer = Color(0xFFD7E2FF),
    secondary = Color(0xFFBEC6DC),
    onSecondary = Color(0xFF283041),
    secondaryContainer = Color(0xFF3F4759),
    onSecondaryContainer = Color(0xFFDAE2F9),
    tertiary = Color(0xFFDDBCE0),
    onTertiary = Color(0xFF3F2844),
    tertiaryContainer = Color(0xFF573E5B),
    onTertiaryContainer = Color(0xFFFAD8FD),
    error = Color(0xFFFFB4AB),
    onError = Color(0xFF690005),
    errorContainer = Color(0xFF93000A),
    onErrorContainer = Color(0xFFFFDAD6),
    background = Color(0xFF1B1B1F),
    onBackground = Color(0xFFE4E2E6),
    surface = Color(0xFF1B1B1F),
    onSurface = Color(0xFFE4E2E6),
    surfaceVariant = Color(0xFF44474F),
    onSurfaceVariant = Color(0xFFC4C6D0),
    outline = Color(0xFF8E9099),
    outlineVariant = Color(0xFF44474F),
    scrim = Color(0xFF000000),
    inverseSurface = Color(0xFFE4E2E6),
    inverseOnSurface = Color(0xFF303034),
    inversePrimary = Color(0xFF005CBC),
    surfaceDim = Color(0xFF1B1B1F),
    surfaceBright = Color(0xFF3A3A3E),
    surfaceContainerLowest = Color(0xFF161619),
    surfaceContainerLow = Color(0xFF1B1B1F),
    surfaceContainer = Color(0xFF202024),
    surfaceContainerHigh = Color(0xFF2A2A2E),
    surfaceContainerHighest = Color(0xFF353538),
)

// ============= GREEN (#16a34a) =============
private val GreenLight = lightColorScheme(
    primary = Color(0xFF006E26),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFF6BFF7F),
    onPrimaryContainer = Color(0xFF002106),
    secondary = Color(0xFF52634F),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFD5E8CE),
    onSecondaryContainer = Color(0xFF111F0F),
    tertiary = Color(0xFF38656A),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFBCEBF0),
    onTertiaryContainer = Color(0xFF002023),
    error = Color(0xFFBA1A1A),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFFFDAD6),
    onErrorContainer = Color(0xFF410002),
    background = Color(0xFFFCFDF7),
    onBackground = Color(0xFF1A1C19),
    surface = Color(0xFFFCFDF7),
    onSurface = Color(0xFF1A1C19),
    surfaceVariant = Color(0xFFDEE5D9),
    onSurfaceVariant = Color(0xFF424940),
    outline = Color(0xFF72796F),
    outlineVariant = Color(0xFFC2C9BD),
    scrim = Color(0xFF000000),
    inverseSurface = Color(0xFF2F312D),
    inverseOnSurface = Color(0xFFF0F1EB),
    inversePrimary = Color(0xFF4BE166),
    surfaceDim = Color(0xFFD9DBD5),
    surfaceBright = Color(0xFFFCFDF7),
    surfaceContainerLowest = Color(0xFFFFFFFF),
    surfaceContainerLow = Color(0xFFF6F6F0),
    surfaceContainer = Color(0xFFF0F1EB),
    surfaceContainerHigh = Color(0xFFEAEBE5),
    surfaceContainerHighest = Color(0xFFE5E6E0),
)

private val GreenDark = darkColorScheme(
    primary = Color(0xFF4BE166),
    onPrimary = Color(0xFF00390F),
    primaryContainer = Color(0xFF00531A),
    onPrimaryContainer = Color(0xFF6BFF7F),
    secondary = Color(0xFFB9CCB3),
    onSecondary = Color(0xFF243424),
    secondaryContainer = Color(0xFF3A4B39),
    onSecondaryContainer = Color(0xFFD5E8CE),
    tertiary = Color(0xFFA1CFD4),
    onTertiary = Color(0xFF00363B),
    tertiaryContainer = Color(0xFF1F4D52),
    onTertiaryContainer = Color(0xFFBCEBF0),
    error = Color(0xFFFFB4AB),
    onError = Color(0xFF690005),
    errorContainer = Color(0xFF93000A),
    onErrorContainer = Color(0xFFFFDAD6),
    background = Color(0xFF1A1C19),
    onBackground = Color(0xFFE2E3DD),
    surface = Color(0xFF1A1C19),
    onSurface = Color(0xFFE2E3DD),
    surfaceVariant = Color(0xFF424940),
    onSurfaceVariant = Color(0xFFC2C9BD),
    outline = Color(0xFF8C9389),
    outlineVariant = Color(0xFF424940),
    scrim = Color(0xFF000000),
    inverseSurface = Color(0xFFE2E3DD),
    inverseOnSurface = Color(0xFF2F312D),
    inversePrimary = Color(0xFF006E26),
    surfaceDim = Color(0xFF1A1C19),
    surfaceBright = Color(0xFF40443F),
    surfaceContainerLowest = Color(0xFF151713),
    surfaceContainerLow = Color(0xFF1A1C19),
    surfaceContainer = Color(0xFF1E201D),
    surfaceContainerHigh = Color(0xFF282B27),
    surfaceContainerHighest = Color(0xFF333532),
)

// ============= PURPLE (#7c3aed) =============
private val PurpleLight = lightColorScheme(
    primary = Color(0xFF5F36AB),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFEADDFF),
    onPrimaryContainer = Color(0xFF1C0054),
    secondary = Color(0xFF635B70),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFE9DEF8),
    onSecondaryContainer = Color(0xFF1F182B),
    tertiary = Color(0xFF7F525A),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFFFD9DE),
    onTertiaryContainer = Color(0xFF321018),
    error = Color(0xFFBA1A1A),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFFFDAD6),
    onErrorContainer = Color(0xFF410002),
    background = Color(0xFFFEF7FF),
    onBackground = Color(0xFF1D1B20),
    surface = Color(0xFFFEF7FF),
    onSurface = Color(0xFF1D1B20),
    surfaceVariant = Color(0xFFE7E0EB),
    onSurfaceVariant = Color(0xFF49454E),
    outline = Color(0xFF7A757F),
    outlineVariant = Color(0xFFCBC4CF),
    scrim = Color(0xFF000000),
    inverseSurface = Color(0xFF322F35),
    inverseOnSurface = Color(0xFFF5EFF7),
    inversePrimary = Color(0xFFD1BCFF),
    surfaceDim = Color(0xFFDED8E0),
    surfaceBright = Color(0xFFFEF7FF),
    surfaceContainerLowest = Color(0xFFFFFFFF),
    surfaceContainerLow = Color(0xFFF8F1FA),
    surfaceContainer = Color(0xFFF2ECF4),
    surfaceContainerHigh = Color(0xFFEDE6EE),
    surfaceContainerHighest = Color(0xFFE7E0E8),
)

private val PurpleDark = darkColorScheme(
    primary = Color(0xFFD1BCFF),
    onPrimary = Color(0xFF3D168C),
    primaryContainer = Color(0xFF471DA2),
    onPrimaryContainer = Color(0xFFEADDFF),
    secondary = Color(0xFFCDC2DB),
    onSecondary = Color(0xFF342D40),
    secondaryContainer = Color(0xFF4B4358),
    onSecondaryContainer = Color(0xFFE9DEF8),
    tertiary = Color(0xFFF2B7C0),
    onTertiary = Color(0xFF4B252D),
    tertiaryContainer = Color(0xFF653B43),
    onTertiaryContainer = Color(0xFFFFD9DE),
    error = Color(0xFFFFB4AB),
    onError = Color(0xFF690005),
    errorContainer = Color(0xFF93000A),
    onErrorContainer = Color(0xFFFFDAD6),
    background = Color(0xFF1D1B20),
    onBackground = Color(0xFFE7E1E8),
    surface = Color(0xFF1D1B20),
    onSurface = Color(0xFFE7E1E8),
    surfaceVariant = Color(0xFF49454E),
    onSurfaceVariant = Color(0xFFCBC4CF),
    outline = Color(0xFF948F99),
    outlineVariant = Color(0xFF49454E),
    scrim = Color(0xFF000000),
    inverseSurface = Color(0xFFE7E1E8),
    inverseOnSurface = Color(0xFF322F35),
    inversePrimary = Color(0xFF5F36AB),
    surfaceDim = Color(0xFF1D1B20),
    surfaceBright = Color(0xFF434046),
    surfaceContainerLowest = Color(0xFF18161B),
    surfaceContainerLow = Color(0xFF1D1B20),
    surfaceContainer = Color(0xFF211F24),
    surfaceContainerHigh = Color(0xFF2B292F),
    surfaceContainerHighest = Color(0xFF36343A),
)

// ============= ORANGE (#ea580c) =============
private val OrangeLight = lightColorScheme(
    primary = Color(0xFF8F4E00),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFFFDCC2),
    onPrimaryContainer = Color(0xFF2E1500),
    secondary = Color(0xFF725945),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFFEDDBF),
    onSecondaryContainer = Color(0xFF291805),
    tertiary = Color(0xFF58633A),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFDCE9B4),
    onTertiaryContainer = Color(0xFF161E00),
    error = Color(0xFFBA1A1A),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFFFDAD6),
    onErrorContainer = Color(0xFF410002),
    background = Color(0xFFFFF8F5),
    onBackground = Color(0xFF211A14),
    surface = Color(0xFFFFF8F5),
    onSurface = Color(0xFF211A14),
    surfaceVariant = Color(0xFFF3DFD2),
    onSurfaceVariant = Color(0xFF52443B),
    outline = Color(0xFF847469),
    outlineVariant = Color(0xFFD6C3B7),
    scrim = Color(0xFF000000),
    inverseSurface = Color(0xFF372F28),
    inverseOnSurface = Color(0xFFFDEEE3),
    inversePrimary = Color(0xFFFFB77C),
    surfaceDim = Color(0xFFE5D8CE),
    surfaceBright = Color(0xFFFFF8F5),
    surfaceContainerLowest = Color(0xFFFFFFFF),
    surfaceContainerLow = Color(0xFFFFF1EA),
    surfaceContainer = Color(0xFFFAEBE0),
    surfaceContainerHigh = Color(0xFFF4E5DA),
    surfaceContainerHighest = Color(0xFFEEE0D5),
)

private val OrangeDark = darkColorScheme(
    primary = Color(0xFFFFB77C),
    onPrimary = Color(0xFF4D2700),
    primaryContainer = Color(0xFF6D3A00),
    onPrimaryContainer = Color(0xFFFFDCC2),
    secondary = Color(0xFFE1C1A4),
    onSecondary = Color(0xFF402C18),
    secondaryContainer = Color(0xFF59422D),
    onSecondaryContainer = Color(0xFFFEDDBF),
    tertiary = Color(0xFFC0CD9A),
    onTertiary = Color(0xFF2B3411),
    tertiaryContainer = Color(0xFF414B26),
    onTertiaryContainer = Color(0xFFDCE9B4),
    error = Color(0xFFFFB4AB),
    onError = Color(0xFF690005),
    errorContainer = Color(0xFF93000A),
    onErrorContainer = Color(0xFFFFDAD6),
    background = Color(0xFF211A14),
    onBackground = Color(0xFFEEE0D5),
    surface = Color(0xFF211A14),
    onSurface = Color(0xFFEEE0D5),
    surfaceVariant = Color(0xFF52443B),
    onSurfaceVariant = Color(0xFFD6C3B7),
    outline = Color(0xFF9F8D82),
    outlineVariant = Color(0xFF52443B),
    scrim = Color(0xFF000000),
    inverseSurface = Color(0xFFEEE0D5),
    inverseOnSurface = Color(0xFF372F28),
    inversePrimary = Color(0xFF8F4E00),
    surfaceDim = Color(0xFF211A14),
    surfaceBright = Color(0xFF493F37),
    surfaceContainerLowest = Color(0xFF1C150F),
    surfaceContainerLow = Color(0xFF211A14),
    surfaceContainer = Color(0xFF261E18),
    surfaceContainerHigh = Color(0xFF302921),
    surfaceContainerHighest = Color(0xFF3C332C),
)

// ============= PINK (#db2777) =============
private val PinkLight = lightColorScheme(
    primary = Color(0xFF8F004F),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFFFD9E2),
    onPrimaryContainer = Color(0xFF3E001F),
    secondary = Color(0xFF73565E),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFFFD9E2),
    onSecondaryContainer = Color(0xFF2A151C),
    tertiary = Color(0xFF7D5636),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFFFDCC4),
    onTertiaryContainer = Color(0xFF2F1500),
    error = Color(0xFFBA1A1A),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFFFDAD6),
    onErrorContainer = Color(0xFF410002),
    background = Color(0xFFFFF8F8),
    onBackground = Color(0xFF21181B),
    surface = Color(0xFFFFF8F8),
    onSurface = Color(0xFF21181B),
    surfaceVariant = Color(0xFFF2DDE3),
    onSurfaceVariant = Color(0xFF514348),
    outline = Color(0xFF837378),
    outlineVariant = Color(0xFFD5C1C7),
    scrim = Color(0xFF000000),
    inverseSurface = Color(0xFF372D30),
    inverseOnSurface = Color(0xFFFDEDF1),
    inversePrimary = Color(0xFFFFB0C8),
    surfaceDim = Color(0xFFE5D6DA),
    surfaceBright = Color(0xFFFFF8F8),
    surfaceContainerLowest = Color(0xFFFFFFFF),
    surfaceContainerLow = Color(0xFFFFF0F3),
    surfaceContainer = Color(0xFFF9EAED),
    surfaceContainerHigh = Color(0xFFF3E4E8),
    surfaceContainerHighest = Color(0xFFEDDFE2),
)

private val PinkDark = darkColorScheme(
    primary = Color(0xFFFFB0C8),
    onPrimary = Color(0xFF5B1131),
    primaryContainer = Color(0xFF7B2948),
    onPrimaryContainer = Color(0xFFFFD9E2),
    secondary = Color(0xFFE1BDC7),
    onSecondary = Color(0xFF422932),
    secondaryContainer = Color(0xFF5A3F48),
    onSecondaryContainer = Color(0xFFFFD9E2),
    tertiary = Color(0xFFF0BC96),
    onTertiary = Color(0xFF48290D),
    tertiaryContainer = Color(0xFF613F21),
    onTertiaryContainer = Color(0xFFFFDCC4),
    error = Color(0xFFFFB4AB),
    onError = Color(0xFF690005),
    errorContainer = Color(0xFF93000A),
    onErrorContainer = Color(0xFFFFDAD6),
    background = Color(0xFF21181B),
    onBackground = Color(0xFFEDDFE2),
    surface = Color(0xFF21181B),
    onSurface = Color(0xFFEDDFE2),
    surfaceVariant = Color(0xFF514348),
    onSurfaceVariant = Color(0xFFD5C1C7),
    outline = Color(0xFF9D8F93),
    outlineVariant = Color(0xFF514348),
    scrim = Color(0xFF000000),
    inverseSurface = Color(0xFFEDDFE2),
    inverseOnSurface = Color(0xFF372D30),
    inversePrimary = Color(0xFF8F004F),
    surfaceDim = Color(0xFF21181B),
    surfaceBright = Color(0xFF483E41),
    surfaceContainerLowest = Color(0xFF1C1316),
    surfaceContainerLow = Color(0xFF21181B),
    surfaceContainer = Color(0xFF261C1F),
    surfaceContainerHigh = Color(0xFF31262A),
    surfaceContainerHighest = Color(0xFF3C3135),
)

/**
 * Get the light color scheme for a given seed preset
 */
fun lightColorSchemeFor(preset: SeedPreset): ColorScheme {
    return when (preset) {
        SeedPreset.TEAL -> TealLight
        SeedPreset.BLUE -> BlueLight
        SeedPreset.GREEN -> GreenLight
        SeedPreset.PURPLE -> PurpleLight
        SeedPreset.ORANGE -> OrangeLight
        SeedPreset.PINK -> PinkLight
        SeedPreset.CUSTOM -> TealLight // Fallback, custom uses dynamic generation
    }
}

/**
 * Get the dark color scheme for a given seed preset
 */
fun darkColorSchemeFor(preset: SeedPreset): ColorScheme {
    return when (preset) {
        SeedPreset.TEAL -> TealDark
        SeedPreset.BLUE -> BlueDark
        SeedPreset.GREEN -> GreenDark
        SeedPreset.PURPLE -> PurpleDark
        SeedPreset.ORANGE -> OrangeDark
        SeedPreset.PINK -> PinkDark
        SeedPreset.CUSTOM -> TealDark // Fallback, custom uses dynamic generation
    }
}

/**
 * Paid key color override options
 * These override colorSecondaryContainer for operator/digit keys
 */
object KeyColorOptions {
    val DARK_GRAY = 0xFF222222.toInt()
    val LIGHT_GREEN = 0xFF86EFAC.toInt()
    val LIME = 0xFFBEF264.toInt()
    val YELLOW = 0xFFFDE047.toInt()
    val MINT = 0xFF6EE7B7.toInt()
    val TEAL = 0xFF1ABC9C.toInt()

    val allColors = listOf(DARK_GRAY, LIGHT_GREEN, LIME, YELLOW, MINT, TEAL)
}
